export const TRACKER_ROUTE_PATHS = {
  ROOT: '/',
  SUMMARY: '/summary',
  DOMAINS: '/domains',

  TRACKER_BY_ID: '/:trackerId',
  REPORT_TRACKER: '/:trackerId/report',
  ARCHIVE_TRACKER: '/:trackerId/archive',
  RESTORE_TRACKER: '/:trackerId/restore',
  PUBLISH_TRACKER: '/:trackerId/publish',
  UNPUBLISH_TRACKER: '/:trackerId/unpublish',
  ROADMAP: '/:trackerId/roadmap',
  CLAN: '/:trackerId/clan',
  CLAN_JOIN: '/:trackerId/clan/join',
  CLAN_JOIN_REQUEST: '/:trackerId/clan/join-requests/:requestId',
  CLAN_MEMBER: '/:trackerId/clan/members/:memberId',
  CLAN_LEAVE: '/:trackerId/clan/leave',
  CLAN_TRANSFER: '/:trackerId/clan/transfer-ownership',
  CLAN_ROLE_INVITATION: '/:trackerId/clan/role-invitations/:invitationId',
  CLAN_SYNC_CLONE: '/:trackerId/clan/fetch-changes',
  CLAN_MESSAGES: '/:trackerId/clan/messages',
  ACTIVE_CLAN_CHALLENGE: '/clan/challenges/active',
  CLAN_CHALLENGES: '/:trackerId/clan/challenges',
  CLAN_CHALLENGE: '/:trackerId/clan/challenges/:challengeId',
  CLAN_CHALLENGE_HISTORY: '/:trackerId/clan/challenges/:challengeId/history',
  CLAN_CHALLENGE_ACCEPT: '/:trackerId/clan/challenges/:challengeId/accept',
  CLAN_CHALLENGE_DECLINE: '/:trackerId/clan/challenges/:challengeId/decline',
  CLAN_CHALLENGE_CANCEL: '/:trackerId/clan/challenges/:challengeId/cancel',
  CLAN_CHALLENGE_QUIT: '/:trackerId/clan/challenges/:challengeId/quit',
  CLAN_CHALLENGE_EXTEND: '/:trackerId/clan/challenges/:challengeId/questions',
  CLAN_CHALLENGE_SUBMIT: '/:trackerId/clan/challenges/:challengeId/submit',
  CLAN_CHALLENGE_CHECKPOINT: '/:trackerId/clan/challenges/:challengeId/checkpoint',
  CLAN_CHALLENGE_ANSWER: '/:trackerId/clan/challenges/:challengeId/answer',
  CLAN_CHALLENGE_POWER: '/:trackerId/clan/challenges/:challengeId/power',

  TOPICS: '/:trackerId/topics',
  IMPORT_OUTLINE: '/:trackerId/outline/import',
  TOPIC_BY_ID: '/:trackerId/topics/:topicId',
  SUBTOPICS: '/:trackerId/topics/:topicId/subtopics',
  SUBTOPIC_BY_ID: '/:trackerId/subtopics/:subtopicId',
  CREATE_TOPIC_CONTRIBUTION: '/:trackerId/topics/:topicId/contributions',
  TOPIC_CONTRIBUTIONS: '/:trackerId/topic-contributions',
  REVIEW_TOPIC_CONTRIBUTION: '/:trackerId/topic-contributions/:contributionId',
  SUBTOPIC_PROGRESS: '/:trackerId/subtopics/:subtopicId/progress',
  VERIFY_TOPIC: '/:trackerId/topics/verify',
  VERIFY_SUBTOPIC: '/:trackerId/topics/:topicId/subtopics/verify',
  ADD_MISSING_EVALUATION_TOPIC:
    '/:trackerId/evaluation-jobs/:evaluationJobId/missing-topics/:topicIndex/add',

  LESSON: '/:trackerId/lessons/:subtopicId',
  LESSON_CHAT: '/:trackerId/lessons/:subtopicId/chat',
  LESSON_QUESTIONS: '/:trackerId/lessons/:subtopicId/questions',
  GENERATE_LESSON_QUESTIONS: '/:trackerId/lessons/:subtopicId/questions/generate',
  LESSON_QUESTION_SOLUTION: '/:trackerId/lessons/:subtopicId/question-solution',
  GENERATE_LESSON_QUESTION_SOLUTION: '/:trackerId/lessons/:subtopicId/question-solution/generate',
  LESSON_QUESTION_SOLUTION_DOUBTS: '/:trackerId/lessons/:subtopicId/question-solution/doubts',
  LESSON_VISUALIZATION: '/:trackerId/lessons/:subtopicId/visualize',

  LESSON_ANSWER_ATTEMPTS: '/:trackerId/lessons/:subtopicId/answer/attempts',
  VERIFY_LESSON_ANSWER: '/:trackerId/lessons/:subtopicId/answer/verify',

  LESSON_CODE_SUBMISSIONS: '/:trackerId/lessons/:subtopicId/code/submissions',
  RUN_LESSON_CODE: '/:trackerId/lessons/:subtopicId/code/run',
  SUBMIT_LESSON_CODE: '/:trackerId/lessons/:subtopicId/code/submit',
  CODE_HINT: '/:trackerId/lessons/:subtopicId/code/hint',
  OPTIMIZED_SOLUTION: '/:trackerId/lessons/:subtopicId/code/optimized-solution',
} as const;

export type TrackerRoutePath = (typeof TRACKER_ROUTE_PATHS)[keyof typeof TRACKER_ROUTE_PATHS];
