export const ROUTES = {
  home: '/',
  register: '/register',
  login: '/login',
  forgotPassword: '/forgot-password',
  verifyAccount: '/verify-account',
  resetPassword: '/reset-password',
  verifyEmailChange: '/verify-email-change',
  twoFactorChallenge: '/two-factor-challenge',
  blocked: '/blocked',
  offline: '/offline',
  privacy: '/privacy',
  terms: '/terms',
  dashboard: '/dashboard',
  profile: '/profile',
  publicProfile: '/profile/:username',
  publicProfileFor: (username: string) => `/profile/${username}`,
  settingsRoot: '/settings',
  learningAgent: '/learning-agent',
  settingsSecurity: '/settings/security',
  settingsNotifications: '/settings/notifications',
  notifications: '/notifications',
  settingsPreferences: '/settings/preferences',
  settingsPrivacy: '/settings/privacy',
  trackers: '/trackers',
  publishedTrackers: '/trackers/published',
  trackerManagePattern: '/trackers/:trackerId/manage',
  trackerRoadmapPattern: '/trackers/:trackerId/roadmap',
  trackerClanPattern: '/trackers/:trackerId/clan',
  trackerClanBattlePattern: '/trackers/:trackerId/clan/challenges/:challengeId',
  trackerManage: (trackerId: string) => `/trackers/${trackerId}/manage`,
  trackerRoadmap: (trackerId: string) => `/trackers/${trackerId}/roadmap`,
  trackerClan: (trackerId: string) => `/trackers/${trackerId}/clan`,
  trackerClanBattle: (trackerId: string, challengeId: string) =>
    `/trackers/${trackerId}/clan/challenges/${challengeId}`,
  community: '/community',
  communityTrackerPattern: '/community/trackers/:trackerId',
  communityTracker: (trackerId: string) => `/community/trackers/${trackerId}`,
  communityVerificationPattern: '/community/verify/:submissionId',
  communityVerification: (submissionId: string) => `/community/verify/${submissionId}`,
  verifyAndEarn: '/verify-and-earn',
  leaderboard: '/leaderboard',
  leaderboardRewards: '/leaderboard/rewards',
  activity: '/activity',
  saved: '/saved',
  pricing: '/pricing',
  support: '/support',
  chat: '/chat',
  friends: '/friends',
  friendsSearch: '/friends/search',
  mockTests: '/mock-tests',
  mockTestGeneratingPattern: '/mock-tests/generating/:jobId',
  mockTestGenerating: (jobId: string) => `/mock-tests/generating/${jobId}`,
  mockTestResultPattern: '/mock-tests/attempts/:attemptId/result',
  mockTestResult: (attemptId: string) => `/mock-tests/attempts/${attemptId}/result`,
  mockTestAnalysisPattern: '/mock-tests/attempts/:attemptId/analysis',
  mockTestAnalysis: (attemptId: string) => `/mock-tests/attempts/${attemptId}/analysis`,
  mockTestDetailPattern: '/mock-tests/:testId',
  mockTestDetail: (testId: string) => `/mock-tests/${testId}`,
  mockTestAttemptPattern: '/mock-tests/attempts/:attemptId',
  mockTestAttempt: (attemptId: string) => `/mock-tests/attempts/${attemptId}`,
  trackerLessonPattern: '/trackers/:trackerId/lessons/:subtopicId',
  trackerLesson: (trackerId: string, subtopicId: string) =>
    `/trackers/${trackerId}/lessons/${subtopicId}`,
  trackerRevisionPattern: '/trackers/:trackerId/revision',
  trackerRevision: (trackerId: string) => `/trackers/${trackerId}/revision`,
  trackerCreate: '/trackers/create',
  trackerCreateAi: '/trackers/create/ai',
  trackerCreateManual: '/trackers/create/manual',
  trackerCreateGeneratingPattern: '/trackers/create/generating/:jobId',
  trackerCreateGenerating: (jobId: string) => `/trackers/create/generating/${jobId}`,
  trackerCreateReadyPattern: '/trackers/create/ready/:jobId',
  trackerCreateReady: (jobId: string) => `/trackers/create/ready/${jobId}`,
  trackerCreateEvaluationPattern: '/trackers/create/evaluation/:jobId',
  trackerCreateEvaluation: (jobId: string) => `/trackers/create/evaluation/${jobId}`,
  trackerCreateEvaluationScorePattern: '/trackers/create/evaluation/:jobId/score',
  trackerCreateEvaluationScore: (jobId: string) => `/trackers/create/evaluation/${jobId}/score`,
} as const;

export const ADMIN_ROUTES = {
  dashboard: '/admin',
  users: '/admin/users',
  userAppeals: '/admin/users/appeals',
  userDetailPattern: '/admin/users/:userId',
  userDetail: (userId: string) => `/admin/users/${userId}`,
  trackers: '/admin/trackers',
  trackerReviews: '/admin/trackers/reviews',
  trackerReports: '/admin/trackers/reports',
  publishedTrackers: '/admin/trackers/published',
  trackerDetailPattern: '/admin/trackers/:trackerId',
  trackerDetail: (trackerId: string) => `/admin/trackers/${trackerId}`,
  mockTests: '/admin/mock-tests',
  mockTestReports: '/admin/mock-tests/reports',
  questionBank: '/admin/mock-tests/question-bank',
  mockTestDetailPattern: '/admin/mock-tests/:testId',
  mockTestDetail: (testId: string) => `/admin/mock-tests/${testId}`,
  legacyTrackerReviews: '/admin/tracker-reviews',
  activity: '/admin/activity',
  legacyAnalytics: '/admin/analytics',
  broadcast: '/admin/broadcast',
  subscriptions: '/admin/subscriptions',
  auditLogs: '/admin/audit-logs',
  systemHealth: '/admin/system-health',
  aiTokenSpend: '/admin/ai-token-spend',
  supportTickets: '/admin/support-tickets',
  settings: '/admin/settings',
  legacySupport: '/admin/support',
} as const;

const PUBLIC_EXACT_PATHS = new Set<string>([
  ROUTES.home,
  ROUTES.register,
  ROUTES.login,
  ROUTES.forgotPassword,
  ROUTES.verifyAccount,
  ROUTES.resetPassword,
  ROUTES.verifyEmailChange,
  ROUTES.twoFactorChallenge,
  ROUTES.blocked,
  ROUTES.offline,
  ROUTES.privacy,
  ROUTES.terms,
]);

export const isPublicRoute = (pathname: string) =>
  PUBLIC_EXACT_PATHS.has(pathname) ||
  (pathname.startsWith(`${ROUTES.profile}/`) && pathname !== ROUTES.profile);
