export const COMMUNITY_DEFAULT_PAGE = 1;
export const COMMUNITY_DEFAULT_LIMIT = 12;
export const COMMUNITY_MAX_LIMIT = 50;
export const COMMUNITY_MAX_SEARCH_LENGTH = 120;

export const COMMUNITY_DEFAULT_LEADERBOARD_LIMIT = 5;
export const COMMUNITY_MAX_LEADERBOARD_LIMIT = 20;

export const COMMUNITY_VERIFICATION_MAX_REQUIRED_VOTES = 50;
export const COMMUNITY_VERIFICATION_MAX_DURATION_HOURS = 168;
