services:
  piston:
    image: ghcr.io/arjunpj-11/imminiq-piston:latest
    container_name: piston_api
    restart: always
    privileged: true
    ports:
      - "2000:2000"
    tmpfs:
      - /tmp:exec