const routeNames: Array<[RegExp, string]> = [
  [/^\/admin\/users\/appeals\/?$/, 'User appeals · Admin'],
  [/^\/admin\/users\/[^/]+\/?$/, 'User details · Admin'],
  [/^\/admin\/users\/?$/, 'Users · Admin'],
  [/^\/admin\/trackers\/reviews\/?$/, 'Verification queue · Admin'],
  [/^\/admin\/tracker-reviews\/?$/, 'Verification queue · Admin'],
  [/^\/admin\/trackers\/reports\/?$/, 'Tracker report queue · Admin'],
  [/^\/admin\/trackers\/published\/?$/, 'Published trackers · Admin'],
  [/^\/admin\/trackers\/[^/]+\/?$/, 'Tracker details · Admin'],
  [/^\/admin\/trackers\/?$/, 'Trackers · Admin'],
  [/^\/admin\/mock-tests\/reports\/?$/, 'Question report queue · Admin'],
  [/^\/admin\/mock-tests\/question-bank\/?$/, 'Question bank · Admin'],
  [/^\/admin\/mock-tests\/[^/]+\/?$/, 'Mock test details · Admin'],
  [/^\/admin\/mock-tests\/?$/, 'Mock tests · Admin'],
  [/^\/admin\/(?:activity|analytics)\/?$/, 'Platform activity · Admin'],
  [/^\/admin\/broadcast\/?$/, 'Broadcast · Admin'],
  [/^\/admin\/subscriptions\/?$/, 'Subscriptions · Admin'],
  [/^\/admin\/audit-logs\/?$/, 'Audit logs · Admin'],
  [/^\/admin\/system-health\/?$/, 'System health · Admin'],
  [/^\/admin\/ai-token-spend\/?$/, 'AI token spend · Admin'],
  [/^\/admin\/(?:support-tickets|support)\/?$/, 'Support tickets · Admin'],
  [/^\/admin\/settings\/?$/, 'Settings · Admin'],
  [/^\/admin\/?$/, 'Dashboard · Admin'],
  [/^\/trackers\/create\/evaluation\/[^/]+\/score\/?$/, 'Roadmap evaluation'],
  [/^\/trackers\/create\/evaluation\/[^/]+\/?$/, 'Roadmap evaluation'],
  [/^\/trackers\/create\/generating\/[^/]+\/?$/, 'Creating tracker'],
  [/^\/trackers\/create\/ready\/[^/]+\/?$/, 'Generated tracker'],
  [/^\/trackers\/create\/manual\/?$/, 'Manual tracker builder'],
  [/^\/trackers\/create\/ai\/?$/, 'AI tracker builder'],
  [/^\/trackers\/create\/?$/, 'Create tracker'],
  [/^\/dashboard\/?$/, 'Dashboard'],
  [/^\/trackers\/published\/?$/, 'Published trackers'],
  [/^\/trackers\/[^/]+\/clan\/challenges\/[^/]+\/?$/, 'Guild battle'],
  [/^\/trackers\/[^/]+\/clan\/?$/, 'Tracker guild'],
  [/^\/trackers\/[^/]+\/lessons\/[^/]+\/?$/, 'Lesson'],
  [/^\/trackers\/[^/]+\/revision\/?$/, 'Quick revision'],
  [/^\/trackers\/[^/]+\/roadmap\/?$/, 'Tracker roadmap'],
  [/^\/trackers\/[^/]+\/manage\/?$/, 'Manage tracker'],
  [/^\/trackers\/?$/, 'Trackers'],
  [/^\/mock-tests\/generating\/[^/]+\/?$/, 'Creating mock test'],
  [/^\/mock-tests\/attempts\/[^/]+\/result\/?$/, 'Mock test result'],
  [/^\/mock-tests\/attempts\/[^/]+\/analysis\/?$/, 'Mock test analysis'],
  [/^\/mock-tests\/attempts\/[^/]+\/?$/, 'Mock test attempt'],
  [/^\/mock-tests\/[^/]+\/?$/, 'Mock test details'],
  [/^\/mock-tests\/?$/, 'Mock tests'],
  [/^\/learning-agent\/?$/, 'Ask Immi'],
  [/^\/community\/verify\/[^/]+\/?$/, 'Community verification'],
  [/^\/community\/trackers\/[^/]+\/?$/, 'Community tracker'],
  [/^\/community\/?$/, 'Community'],
  [/^\/verify-and-earn\/?$/, 'Verify and earn'],
  [/^\/leaderboard\/rewards\/?$/, 'Leaderboard rewards'],
  [/^\/leaderboard\/?$/, 'Leaderboard'],
  [/^\/activity\/?$/, 'Activity'],
  [/^\/saved\/?$/, 'Saved'],
  [/^\/chat\/?$/, 'Social'],
  [/^\/friends\/search\/?$/, 'Find friends'],
  [/^\/friends\/?$/, 'Friends'],
  [/^\/settings(?:\/(?:security|notifications|preferences|privacy))?\/?$/, 'Settings'],
  [/^\/notifications\/?$/, 'Notifications'],
  [/^\/profile(?:\/[^/]+)?\/?$/, 'Profile'],
  [/^\/pricing\/?$/, 'Plans'],
  [/^\/support\/?$/, 'Support'],
  [/^\/login\/?$/, 'Sign in'],
  [/^\/register\/?$/, 'Create account'],
  [/^\/forgot-password\/?$/, 'Password recovery'],
  [/^\/verify-account\/?$/, 'Verify account'],
  [/^\/reset-password\/?$/, 'Reset password'],
  [/^\/verify-email-change\/?$/, 'Verify email change'],
  [/^\/two-factor-challenge\/?$/, 'Two-step verification'],
  [/^\/blocked\/?$/, 'Account restricted'],
  [/^\/offline\/?$/, 'Offline'],
  [/^\/privacy\/?$/, 'Privacy'],
  [/^\/terms\/?$/, 'Terms'],
];

export const getRouteName = (pathname: string) => {
  if (pathname === '/') return 'Imminiq';
  return routeNames.find(([pattern]) => pattern.test(pathname))?.[1] ?? 'Page not found';
};
