export const MODERATION_APPEAL_CASE_ID_PREFIX = 'CASE-IQ'
export const MODERATION_APPEAL_CASE_ID_MIN_RANDOM = 1000
export const MODERATION_APPEAL_CASE_ID_MAX_RANDOM = 10000
export const MODERATION_APPEAL_CASE_ID_GENERATION_MAX_ATTEMPTS = 10
export const MODERATION_APPEAL_IDENTIFIER_MAX_LENGTH = 120
export const MODERATION_APPEAL_REASON_MIN_LENGTH = 10
export const MODERATION_APPEAL_REASON_MAX_LENGTH = 2000
