export const FRIENDS_DEFAULT_PAGE = 1;
export const FRIENDS_DEFAULT_PAGE_SIZE = 20;
export const FRIENDS_MAX_PAGE_SIZE = 50;
export const FRIENDS_SEARCH_MIN_LENGTH = 2;
export const FRIENDS_SEARCH_MAX_LENGTH = 80;
export const FRIEND_REQUEST_MESSAGE_MAX_LENGTH = 280;
