export const DASHBOARD_DEFAULT_RECENT_ACTIVITY_LIMIT = 5;
export const DASHBOARD_DEFAULT_ACTIVITY_MONTHS = 6;
export const DASHBOARD_DEFAULT_RECENT_BATTLES_LIMIT = 5;
export const DASHBOARD_DEFAULT_FRIENDS_LIMIT = 10;
export const DASHBOARD_ACTIVE_TRACKERS_LIMIT = 5;
export const DASHBOARD_MAX_RECENT_ITEMS_LIMIT = 20;
export const DASHBOARD_MAX_RECOMMENDED_ACTIONS = 4;
