import { CommunityVerificationSubmission } from '../../../../../infrastructure/database/models/community-verification-submission.model'
import { Tracker } from '../../../../../infrastructure/database/models/tracker.model'
import { ApiError } from '../../../../../shared/utils/ApiError'
import type { AdminActor, AdminListQuery } from '../../../shared'
import { recordAdminAction } from '../../../shared'
import { createAdminPage, escapeAdminSearch } from '../../../shared'
import type { IAdminTrackerReviewsRepository } from '../../domain/repositories/admin-tracker-reviews.repository.interface'
export class MongoAdminTrackerReviewsRepository implements IAdminTrackerReviewsRepository {
  async list(query: AdminListQuery) { const filter: Record<string, unknown> = { deletedAt: null }; if (query.status && query.status !== 'all') filter.status = query.status; if (query.search) filter.$or = [{ title: new RegExp(escapeAdminSearch(query.search), 'i') }, { category: new RegExp(escapeAdminSearch(query.search), 'i') }]; const [rows, total, open, approved, rejected] = await Promise.all([CommunityVerificationSubmission.find(filter).sort({ urgent: -1, createdAt: -1 }).skip((query.page - 1) * query.limit).limit(query.limit).populate('ownerId', 'fullName username').lean(), CommunityVerificationSubmission.countDocuments(filter), CommunityVerificationSubmission.countDocuments({ deletedAt: null, status: 'open' }), CommunityVerificationSubmission.countDocuments({ deletedAt: null, status: 'approved' }), CommunityVerificationSubmission.countDocuments({ deletedAt: null, status: 'rejected' })]); const items = rows.map((row) => { const owner = row.ownerId as unknown as { fullName?: string; username?: string }; return { id: String(row._id), title: row.title, owner: owner?.fullName ?? owner?.username ?? 'Unknown', category: row.category, status: row.status, urgent: row.urgent, passVotes: row.passVotes, failVotes: row.failVotes, createdAt: row.createdAt } }); return createAdminPage(items, query, total, { open, approved, rejected }) }
  async resolve(id: string, status: string, actor: AdminActor) { const review = await CommunityVerificationSubmission.findOneAndUpdate({ _id: id, deletedAt: null }, { $set: { status, consensusChoice: status === 'approved' ? 'pass' : 'fail' } }, { new: true }).lean(); if (!review) throw new ApiError(404, 'Tracker review not found', 'TRACKER_REVIEW_NOT_FOUND'); await Tracker.updateOne({ _id: review.trackerId }, { $set: { verificationStatus: status === 'approved' ? 'verified' : 'rejected', verifiedAt: status === 'approved' ? new Date() : null } }); await recordAdminAction(actor, 'admin_tracker_review_resolved', 'admin.tracker-reviews', { reviewId: id, status, trackerId: String(review.trackerId) }); return { id, status: review.status } }
}
export const mongoAdminTrackerReviewsRepository = new MongoAdminTrackerReviewsRepository()
