export const API_ROUTE_PATHS = {
  auth: '/api/auth',
  onboarding: '/api/onboarding',
  trackers: '/api/trackers',
  users: '/api/users',
  uploads: '/api/uploads',
  settings: '/api/settings',
  subscriptions: '/api/subscriptions',
  dashboard: '/api/dashboard',
  supportTickets: '/api/support-tickets',
  security: '/api/security',
  mockTests: '/api/mock-tests',
  adaptiveLearning: '/api/adaptive-learning',
  community: '/api/community',
  moderationAppeals: '/api/moderation-appeals',
  leaderboard: '/api/leaderboard',
  activity: '/api/activity',
  friends: '/api/friends',
  notifications: '/api/notifications',
  health: '/api/health',
  healthLive: '/api/health/live',
  healthReady: '/api/health/ready',
  admin: {
    dashboard: '/api/admin/dashboard',
    users: '/api/admin/users',
    trackers: '/api/admin/trackers',
    mockTests: '/api/admin/mock-tests',
    analytics: '/api/admin/analytics',
    broadcasts: '/api/admin/broadcasts',
    auditLogs: '/api/admin/audit-logs',
    systemHealth: '/api/admin/system-health',
    supportTickets: '/api/admin/support-tickets',
    settings: '/api/admin/settings',
    subscriptions: '/api/admin/subscriptions',
    aiTokenSpend: '/api/admin/ai-token-spend',
  },
} as const;
