export const DEFAULT_MOCK_TEST_PAGE = 1;
export const DEFAULT_MOCK_TEST_LIST_LIMIT = 6;
export const DEFAULT_PUBLIC_TEST_LIST_LIMIT = 20;
export const MAX_MOCK_TEST_LIST_LIMIT = 50;
export const MAX_MANUAL_QUESTIONS = 100;
export const DEFAULT_TEST_TIME_LIMIT_MINUTES = 30;
export const DEFAULT_PASSING_SCORE = 60;
