import { MockTestModel } from '../../../../../infrastructure/database/models/mock-test.model'
import { MockTestAttemptModel } from '../../../../../infrastructure/database/models/mock-test-attempt.model'
import { MockTestQuestionModel } from '../../../../../infrastructure/database/models/mock-test-question.model'
import type { AdminListQuery } from '../../../shared'
import { createAdminPage, escapeAdminSearch } from '../../../shared'
import type { IAdminMockTestsRepository } from '../../domain/repositories/admin-mock-tests.repository.interface'
export class MongoAdminMockTestsRepository implements IAdminMockTestsRepository {
  async list(query: AdminListQuery) { const filter: Record<string, unknown> = {}; if (query.status && query.status !== 'all') filter.visibility = query.status; if (query.search) filter.title = new RegExp(escapeAdminSearch(query.search), 'i'); const [rows, total, publicCount, privateCount, attempts] = await Promise.all([MockTestModel.find(filter).sort({ createdAt: -1 }).skip((query.page - 1) * query.limit).limit(query.limit).populate('ownerId', 'fullName username').lean(), MockTestModel.countDocuments(filter), MockTestModel.countDocuments({ visibility: 'public' }), MockTestModel.countDocuments({ visibility: 'private' }), MockTestAttemptModel.countDocuments()]); const items = rows.map((row) => { const owner = row.ownerId as unknown as { fullName?: string; username?: string }; return { id: String(row._id), title: row.title, owner: owner?.fullName ?? owner?.username ?? 'Unknown', difficulty: row.difficulty, visibility: row.visibility, questionCount: row.questionCount, attemptCount: row.attemptCount, averageScore: row.averageScore, isAIGenerated: row.isAIGenerated, createdAt: row.createdAt } }); return createAdminPage(items, query, total, { public: publicCount, private: privateCount, attempts }) }
  async getDetail(id: string) { const [test, questions] = await Promise.all([MockTestModel.findById(id).populate('ownerId', 'fullName username').lean(), MockTestQuestionModel.find({ testId: id }).sort({ order: 1 }).lean()]); if (!test) return null; const owner = test.ownerId as unknown as { fullName?: string; username?: string }; return { id: String(test._id), title: test.title, description: test.description, owner: owner?.fullName ?? owner?.username ?? 'Unknown', difficulty: test.difficulty, visibility: test.visibility, questionCount: test.questionCount, attemptCount: test.attemptCount, averageScore: test.averageScore, isAIGenerated: test.isAIGenerated, createdAt: test.createdAt, timeLimitMinutes: test.timeLimitMinutes, passingScore: test.passingScore, tags: test.tags, questions: questions.map((question) => ({ id: String(question._id), order: question.order, type: question.type, question: question.question, ...(question.options ? { options: question.options } : {}), ...(question.correctAnswer ? { correctAnswer: question.correctAnswer } : {}), ...(question.explanation ? { explanation: question.explanation } : {}), difficulty: question.difficulty, points: question.points, ...(question.coding ? { coding: { functionName: question.coding.functionName, language: question.coding.language, starterCode: question.coding.starterCode, testCaseCount: question.coding.testCases?.length ?? 0 } } : {}) })) } }
}
export const mongoAdminMockTestsRepository = new MongoAdminMockTestsRepository()
