export const STORAGE_KEYS = {
  auth: 'auth',
  themeMode: 'theme_mode',
  appShell: 'imminiq_app_shell',
  legacySidebar: 'imminiq_sb',
  onboardingDraft: 'imminiq_onboarding_draft',
  trackerCreationDraft: 'imminiq_tracker_creation_draft',
  chatDraftPrefix: 'imminiq_chat_draft',
  chatQueuePrefix: 'imminiq_chat_queue',
  guildChatDraftPrefix: 'imminiq_guild_chat_draft',
  scrollPositionPrefix: 'imminiq_scroll_position',
  recentLesson: 'imminiq_recent_lesson',
  onboardingGuildVisited: 'imminiq_onboarding_guild_visited',
  gettingStartedDismissed: 'imminiq_getting_started_dismissed',
  lessonFeedbackPrefix: 'imminiq_lesson_feedback',
  mockTestAttemptDraftPrefix: 'imminiq_mock_test_attempt_draft',
  supportTicketDraft: 'imminiq_support_ticket_draft',
  lastOnlinePath: 'last_online_path_before_offline',
  dashboardInsightDismissed: 'imminiq_dashboard_insight_dismissed',
  landingIntroPlayed: 'imminiq_landing_intro_played',
  pendingEmailChangeTimer: 'imminiq_pending_email_change_timer',
  blockedAppealIdentifier: 'blocked_appeal_identifier',
  blockedAppealToken: 'blocked_appeal_token',
  blockedModerationMessage: 'blocked_moderation_message',
  authSync: 'imminiq-auth-sync',
  otpExpiry: 'otp_expiry',
  otpResendExpiry: 'otp_resend_expiry',
} as const;
