export const STORAGE_KEYS = {
  auth: 'auth',
  themeMode: 'theme_mode',
  appShell: 'imminiq_app_shell',
  legacySidebar: 'imminiq_sb',
  onboardingDraft: 'imminiq_onboarding_draft',
  trackerCreationDraft: 'imminiq_tracker_creation_draft',
  lastOnlinePath: 'last_online_path_before_offline',
  dashboardInsightDismissed: 'imminiq_dashboard_insight_dismissed',
  landingIntroPlayed: 'imminiq_landing_intro_played',
  pendingEmailChangeTimer: 'imminiq_pending_email_change_timer',
  blockedAppealIdentifier: 'blocked_appeal_identifier',
  blockedAppealToken: 'blocked_appeal_token',
  blockedModerationMessage: 'blocked_moderation_message',
  authSync: 'imminiq-auth-sync',
  otpExpiry: 'otp_expiry',
  otpResendExpiry: 'otp_resend_expiry',
} as const;
