export const COMMUNITY_REVIEW_REWARD_COINS = 50
export const COMMUNITY_URGENT_REVIEW_HOURS = 2

export const COMMUNITY_DEFAULT_PAGE = 1
export const COMMUNITY_DEFAULT_LIMIT = 12
export const COMMUNITY_MAX_LIMIT = 50
export const COMMUNITY_MAX_SEARCH_LENGTH = 120

export const COMMUNITY_DEFAULT_LEADERBOARD_LIMIT = 5
export const COMMUNITY_MAX_LEADERBOARD_LIMIT = 20

export const COMMUNITY_VERIFICATION_DEFAULT_REQUIRED_VOTES = 10
export const COMMUNITY_VERIFICATION_MAX_REQUIRED_VOTES = 50
export const COMMUNITY_VERIFICATION_DEFAULT_DURATION_HOURS = 24
export const COMMUNITY_VERIFICATION_MAX_DURATION_HOURS = 168


export const COMMUNITY_VERIFICATION_VOTE_TEACHER_XP = 30
export const COMMUNITY_VERIFICATION_MAJORITY_TEACHER_XP = 100