import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import Modal from '../../../../components/overlays/Modal';
import api from '../../../../lib/axios';
import { toast } from '../../../../lib/toast';
import { getUserFacingError } from '../../../../lib/user-facing-error';

type Kind = 'users' | 'trackers' | 'mock-tests';
export function AdminBulkActionBar({ kind, selected, onClear }: { kind: Kind; selected: string[]; onClear: () => void }) {
  const [open, setOpen] = useState(false);
  const [action, setAction] = useState<'suspend' | 'delete' | 'restore' | 'block'>('suspend');
  const [reason, setReason] = useState('');
  const [mfaCode, setMfaCode] = useState('');
  const [eligible, setEligible] = useState<string[] | null>(null);
  const client = useQueryClient();
  const endpoint = kind === 'users' ? '/admin/users/bulk/status' : `/admin/${kind}/bulk/lifecycle`;
  const body = (preview: boolean) => kind === 'users' ? { userIds: selected, status: action === 'block' || action === 'restore' ? (action === 'restore' ? 'active' : 'blocked') : 'paused', reasonCode: action === 'restore' ? 'appeal_accepted' : 'other', reason, notifyEmail: true, preview } : { ids: selected, action: action === 'block' ? 'suspend' : action, reasonCode: action === 'restore' ? 'appeal_accepted' : 'other', reason, notifyOwner: true, preview };
  const mutation = useMutation({ mutationFn: async (preview: boolean) => (await api.post(endpoint, body(preview), { headers: mfaCode ? { 'X-Admin-MFA-Code': mfaCode } : undefined })).data.data as { eligible?: string[]; succeeded?: number; failed?: number }, onSuccess: async (data, preview) => { if (preview) setEligible(data.eligible ?? []); else { toast.success('Bulk action completed', `${data.succeeded ?? 0} succeeded; ${data.failed ?? 0} failed.`); setOpen(false); setEligible(null); onClear(); await client.invalidateQueries({ queryKey: ['admin', kind] }); } }, onError: (error) => toast.error('Bulk action failed', getUserFacingError(error)) });
  if (!selected.length) return null;
  return <div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e8816a]/30 bg-[#e8816a]/10 p-4"><strong>{selected.length} selected</strong><div className="flex gap-2"><button className="admin-button" onClick={onClear}>Clear</button><button className="admin-primary-button" onClick={() => setOpen(true)}>Bulk action</button></div><Modal open={open} onClose={() => { setOpen(false); setEligible(null); }} preventClose={mutation.isPending} ariaLabel="Bulk administration action" contentClassName="max-w-xl bg-[#1c1a18] text-[#f2f0eb]"><h2 className="font-editorial text-2xl font-bold">Bulk {kind} action</h2><p className="mt-2 text-sm text-[#aaa59d]">A preview is required before applying changes. Each item records its own audit result and owner notification.</p><label className="admin-field mt-5 block"><span>Action</span><select value={action} onChange={(event) => { setAction(event.target.value as typeof action); setEligible(null); }}><option value="suspend">Suspend</option>{kind === 'users' && <option value="block">Block</option>}{kind !== 'users' && <option value="delete">Delete</option>}<option value="restore">Restore</option></select></label><label className="admin-field mt-4 block"><span>Reason</span><textarea rows={5} minLength={15} maxLength={1000} value={reason} onChange={(event) => { setReason(event.target.value); setEligible(null); }}/></label><label className="admin-field mt-4 block"><span>Authenticator code</span><input inputMode="numeric" value={mfaCode} onChange={(event) => setMfaCode(event.target.value.replace(/\D/g, ''))}/></label>{eligible && <div className="mt-4 rounded-lg border border-white/10 bg-[#24211e] p-4 text-sm"><strong>{eligible.length} of {selected.length}</strong> records are eligible. Review the scope, then apply.</div>}<div className="mt-6 flex justify-end gap-2"><button className="admin-button" onClick={() => setOpen(false)}>Cancel</button>{eligible ? <button className="admin-primary-button" disabled={!eligible.length || mutation.isPending} onClick={() => mutation.mutate(false)}>Apply to {eligible.length}</button> : <button className="admin-primary-button" disabled={reason.trim().length < 15 || mutation.isPending} onClick={() => mutation.mutate(true)}>Preview impact</button>}</div></Modal></div>;
}
