export const CHAT_RESPONSE_MESSAGES = {
  CONVERSATIONS_LISTED: 'Conversations loaded',
  CONVERSATION_READY: 'Conversation ready',
  MESSAGES_LISTED: 'Messages loaded',
  MESSAGE_SENT: 'Message sent',
  CONVERSATION_READ: 'Conversation marked as read',
  MESSAGE_FORWARDED: 'Message forwarded',
  TRACKER_SHARED: 'Tracker shared',
  PROFILE_SHARED: 'Profile shared',
  BLOCKS_LISTED: 'Blocked users loaded',
  USER_BLOCKED: 'User blocked',
  USER_UNBLOCKED: 'User unblocked',
  MESSAGE_STAR_UPDATED: 'Message star updated',
  MESSAGE_REACTION_UPDATED: 'Message reaction updated',
  MESSAGE_EDITED: 'Message edited',
  MESSAGE_DELETED: 'Message deleted',
  SAVED_MESSAGES_LISTED: 'Saved messages loaded',
  CONVERSATION_CLEARED: 'Unstarred messages cleared',
} as const;
