export {
  ACCOUNT_DELETION_RECOVERY_DAYS,
  ACCOUNT_DELETION_RECOVERY_MS,
  EMAIL_CHANGE_TOKEN_EXPIRES_MINUTES,
  TWO_FACTOR_BACKUP_CODE_COUNT,
  TWO_FACTOR_DISABLE_ATTEMPT_SCOPE,
  TWO_FACTOR_ISSUER,
  TWO_FACTOR_SETUP_ATTEMPT_SCOPE,
} from '../domain/security.constants'
