export const LEADERBOARD_DEFAULT_LIMIT = 8;
export const LEADERBOARD_MIN_LIMIT = 3;
export const LEADERBOARD_MAX_LIMIT = 50;
export const LEADERBOARD_TARGET_RANK = 100;
export const LEADERBOARD_STREAK_CHAMPION_LIMIT = 3;
export const LEADERBOARD_WEEKLY_TIER_XP = 5000;
