export const COMMUNITY_REVIEW_REWARD_COINS = 50
export const COMMUNITY_URGENT_REVIEW_HOURS = 2
export const COMMUNITY_DEFAULT_PAGE = 1
export const COMMUNITY_DEFAULT_LIMIT = 12
export const COMMUNITY_MAX_LIMIT = 50
